<a href="https://colab.research.google.com/github/Ayesha-Zaman/Intelligence-Journey-/blob/main/05%3A%20Numpy/%20Numpy%20Fundamentals/%20Task%2013%3A%20Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [ ]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
# code

a = np.nan *np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
# code

a, b= map(int,input('Enter two numbers: ').split())
x = np.random.random((a,b))
print(x)
print(x.mean())

Enter two numbers: 3 4
[[0.74663401 0.83736594 0.20597921 0.19095091]
 [0.76251522 0.91568959 0.48549662 0.13076426]
 [0.08390408 0.33458054 0.2931243  0.60231183]]
0.4657763765365157


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
# code

def border_array(a,b):
  x = np.ones((4,4))
  x[1:-1,1:-1] = 0
  return x


border_array(3,4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
# code

np.linspace(0,1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
# Nope identity matrix must have equal column & rows

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
z = np.ones((5,5))
z*= np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [ ]:
z = np.zeros((5,5))
z+= np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
a = np.random.randint(1,100,(10,2))
p = np.array([2,3])

# Applying euclidean formula
distance = np.sqrt(np.sum((a-p)**2, axis=1)).astype(int)

print(distance)

[100 100  78  93  56  97  79  84  66  85]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
# code

# a = np.zeros((6,7,8))
np.array(np.unravel_index(100,(6,7,8)))

array([1, 5, 4])

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
# code

i = input("Enter space separated numbers: ").strip().split()
np.array(i[::-1], dtype=np.int32)

Enter space separated numbers: 3 4 2 8 -6 -7 1


array([ 1, -7, -6,  8,  2,  4,  3], dtype=int32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
# code

# a = np.array([])
a = np.array([4,5,6])
a = np.random.random((2,3,6))
a.size

36

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
def soft_max(arr):

  if type(arr) != np.ndarray:
    raise TypeError("Required Numpy Array.")
  elif arr.ndim > 1:
    raise TypeError("Required 1D Array.")
  s = np.sum(np.exp(arr))
  return np.exp(arr) / s

soft_max(np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278]
))

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
# code

def vertical_stack(*args):

  for i in args:
    if type(i) != np.ndarray:
      raise TypeError("Required Numpy Array.")
  return np.vstack(args)


a = np.arange(10).reshape(2,-1)
print('a=',a)
b = np.repeat(1,10).reshape(2,-1)
print('b=',b)

print(vertical_stack(a,b))

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# code

def vertical_stack(*args):

  for i in args:
    if type(i) != np.ndarray:
      raise TypeError("Required Numpy Array.")
  return np.vstack(args)


a = np.arange(10).reshape(2,-1)
print('a=',a)
b = np.repeat(1,10).reshape(2,-1)
print('b=',b)
c = np.random.random((2,5))
print('c=',c)

print(vertical_stack(a,b,c))

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.97029219 0.42235569 0.77865234 0.09008713 0.77261576]
 [0.07028164 0.33606075 0.11355357 0.0081202  0.51347776]]
[[0.00000000e+00 1.00000000e+00 2.00000000e+00 3.00000000e+00
  4.00000000e+00]
 [5.00000000e+00 6.00000000e+00 7.00000000e+00 8.00000000e+00
  9.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00]
 [9.70292191e-01 4.22355695e-01 7.78652344e-01 9.00871296e-02
  7.72615758e-01]
 [7.02816447e-02 3.36060745e-01 1.13553571e-01 8.12020324e-03
  5.13477760e-01]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
# code

def date_array(start:str, end:str):
  if type(start) != str or type(end) != str:
    raise TypeError

  total_days_of_month = {'01':31,'02':28,'03':31,'04':30,'05':31,'06':30,'07':31,'08':31,'09':30,'10':31,'11':30,'12':31}

  end = end.split('-')
  end_last = int(end[-1])+1
  if total_days_of_month[end[-2]] < end_last:
    days_diff = end_last - total_days_of_month[end[-2]]
    end[-1] = f'0{days_diff}' if days_diff < 10 else f'{days_diff}'
    next_month = int(end[-2]) + 1
    end[-2] = f'0{next_month}' if next_month < 10 else f'{next_month}'

  else:
    end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
  end = '-'.join(end)

  return np.arange(start,end, dtype="datetime64[D]")

date_array(start = '2020-11-25', end = '2020-11-30')

array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='datetime64[D]')

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
# code

a = np.random.random((5,4))
#print(a)
#print(np.mean(a, axis =1, keepdims=True))
res = a - np.mean(a, axis =1, keepdims=True)
res

array([[-0.34836567,  0.17146624,  0.31704263, -0.14014321],
       [ 0.26547863, -0.04934008, -0.25010333,  0.03396478],
       [ 0.12139775, -0.00395994, -0.37357079,  0.25613298],
       [ 0.37635014, -0.12638319, -0.06501227, -0.18495468],
       [-0.38737499,  0.04681327,  0.41867091, -0.07810918]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
# code

a = np.arange(9).reshape(3,3)
print(a)
a[:,[0,2,1]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
# code

a = np.arange(10)
a[a%2 == 1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
# code

a = np.arange(16).reshape(4,4)
# print(a)
a[a%2 == 1] = -1
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0 -1  2 -1]
 [ 4 -1  6 -1]
 [ 8 -1 10 -1]
 [12 -1 14 -1]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
# code

a=np.array([6,3,1,5,8])
b=np.array([3,5,1,7,2])

a[b>a] = b[a<b]
a

array([6, 5, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# code

arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[9845, 5936, 9483, 1732,  295],
       [7642, 3810, 7814, 8644, 3969],
       [2619, 2882, 1264, 7621, 9771],
       [5156, 1969, 5239, 8230,  255],
       [3558, 9582, 2789, 8358, 4181],
       [ 177, 2097, 3873, 6830, 9959],
       [6091, 7245, 5669, 6652, 7011],
       [1364,    7, 6386, 2536, 2642]])

In [ ]:
# 1. Fetch Every alternate column of the array

arr1[:,::2]

array([[9845, 9483,  295],
       [7642, 7814, 3969],
       [2619, 1264, 9771],
       [5156, 5239,  255],
       [3558, 2789, 4181],
       [ 177, 3873, 9959],
       [6091, 5669, 7011],
       [1364, 6386, 2642]])

In [ ]:
# 2. Normalise the given array

(arr1 - arr1.mean()) / (arr1.max() - arr1.min())

array([[ 0.48386505,  0.09107968,  0.44749045, -0.33134797, -0.47574106],
       [ 0.26250251, -0.12254572,  0.27978547,  0.36318579, -0.10656903],
       [-0.24222016, -0.21579331, -0.37837369,  0.26039238,  0.47642936],
       [ 0.01270348, -0.30753366,  0.02104351,  0.32158611, -0.47976035],
       [-0.14786726,  0.4574382 , -0.22513816,  0.33444785, -0.08526678],
       [-0.48759797, -0.29467193, -0.11621533,  0.18091087,  0.49532004],
       [ 0.10665444,  0.22261103,  0.0642509 ,  0.16302502,  0.19909817],
       [-0.36832546, -0.50467996,  0.13629672, -0.25056019, -0.23990906]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
# code

def nth_max(arr, n):
  if n >= len(arr):
    raise IndexError('n is way out of limit.')
  arr.sort()
  return arr[-n]


print(nth_max(np.array([12,34,40,7,1,0]), 1))

40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
a = np.array([1,2,3])
np.hstack([np.repeat(a,3),np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])