<a href="https://colab.research.google.com/github/Ayesha-Zaman/Intelligence-Journey-/blob/main/05%3A%20Numpy/%20Numpy%20Fundamentals/%20Topic%2013%20Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [ ]:
# np.array

import numpy as np

# 1D or vector
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D and 3D

# 2D or matrices
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D

c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# dtype
np.array([1,2,3], dtype=bool)

array([ True,  True,  True])

In [ ]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [ ]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
# np.arange     -> works exact like range function

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11, 2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# np.ones and np.zeros


# initializin arrays
# utility: toinitialize values,particularly used in deep and machine learning models like neural networks

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# np.random   -> generate random numbers between 0 and 1

np.random.random((3,4))

array([[0.43810477, 0.54136411, 0.34681608, 0.37516101],
       [0.01945889, 0.30785375, 0.8742222 , 0.18351733],
       [0.45656089, 0.83357775, 0.03377057, 0.70266824]])

In [ ]:
# np.linspace
# it generates equal distance points of given range and number

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.linspace(-10,10,10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

# print(a1)
# print(a2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim   -> tells dimension of array

a3.ndim

3

In [ ]:
# shape   -> No. of rows & columns
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size    -> No. of items

a1.size

10

In [ ]:
a2.size
a3.size

8

In [ ]:
# itemsize      -> space occupies in memory by each item

a1.itemsize

8

In [ ]:
print(a2.itemsize)

8


In [ ]:
# in above two cells it has same memory size because:
#   int64 -> 8 bits
#   int32 -> 4 bits

In [ ]:
a1 = np.arange(10, dtype=np.int32)

a1.itemsize

4

In [ ]:
a3.itemsize

8

In [ ]:
# dtype   -> datatype of items

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [ ]:
# astype    -> utility: memory optimization
# Example: if you have age column in your dataset and its dtype is int64, so it's taking unnecessary space.
#          so changing its dtype into int32 will be much more beneficial

In [ ]:
# astype
print(a3)
a3.astype(np.int32)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations   -> works on 1 ndarray & a scalar entity (e.g: 5)

In [ ]:
# Arithmatic

a1 * 5

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [ ]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a1 / 3

array([[0.        , 0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667]])

In [ ]:
a1 // 3

array([[0, 0, 0, 1],
       [1, 1, 2, 2],
       [2, 3, 3, 3]])

In [ ]:
# relational

a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 == 20

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [ ]:
a1 <= 5

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations     -> deals with 2 ndarrays
# arithmetic

a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[86., 50., 62.],
       [22., 85., 61.],
       [15., 14., 85.]])

In [ ]:
# max/min/sum/prod

print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

86.0
14.0
480.0
542837456700000.0


In [ ]:
# max/min/sum/prod
# for specific row or col   -> axis
# 0 -> col and 1-> row

print(np.max(a1, axis=1))
print(np.min(a1, axis=0))
print(np.sum(a1, axis=1))
print(np.prod(a1, axis=0))

[86. 85. 85.]
[15. 14. 61.]
[198. 168. 114.]
[ 28380.  59500. 321470.]


In [ ]:
a1

array([[86., 50., 62.],
       [22., 85., 61.],
       [15., 14., 85.]])

In [ ]:
# mean/median/std/var

print(np.mean(a1))

53.333333333333336


In [ ]:
print(np.std(a1, axis=1))

[14.96662955 25.96150997 33.23652609]


In [ ]:
# trigonomoetric functions

np.sin(a1)

array([[-0.92345845, -0.26237485, -0.7391807 ],
       [-0.00885131, -0.17607562, -0.96611777],
       [ 0.65028784,  0.99060736, -0.17607562]])

In [ ]:
# dot product
#    -> possible if rows of 1st matrix equal to columns of 2nd matrix

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[2.23524660e+37, 5.18470553e+21, 8.43835667e+26],
       [3.58491285e+09, 8.22301271e+36, 3.10429794e+26],
       [3.26901737e+06, 1.20260428e+06, 8.22301271e+36]])

In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[48., 11., 78.],
       [45., 83., 24.]])

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(a1[-1])
print(a1[4])

9
4


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# first select row and then column
print(a2[1,0])
print(a2[2,2])
print(a2[0,1])

4
10
1


In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# -> 1st select 2D array, after that row and column
print(a3[1,0,1])

5


In [ ]:
print(a3[1,1,0])

6


In [ ]:
# Slicing

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,::]

array([0, 1, 2, 3])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1]

array([3, 4, 5])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# nditer()
# Converts any ndarray to 1D ndarray and then,
# itrates through indvidual item.

for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshaping

In [ ]:
# transpose     -> converts rows to coulmns & columns to rows
print(a2)
np.transpose(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# another way

a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel     -> Converts any ndarray to 1D ndarray
a3.ravel()
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [ ]:
# stacking utility
# when data coming from multiple sources and have to analyze all data.
# like from database, through APIs etc, so we 1st stack it and then analyze

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# splitting performs exact opposite of stacking
# sepration must be in equal parts

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.hsplit(a4,3)   # error: bcz not in equal parts

ValueError: array split does not result in an equal division

In [ ]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [ ]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division