<a href="https://colab.research.google.com/github/Ayesha-Zaman/Intelligence-Journey-/blob/main/05%3A%20Numpy/%20Numpy%20Tricks/%20Topic%2015%20Numpy_Tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 2, 61, 37, 74],
       [45,  6,  2, 23],
       [ 6, 71, 77, 38],
       [15, 73, 63, 39],
       [12, 21, 87, 27],
       [25, 95, 28, 63]])

In [4]:
np.sort(a)

array([ 3,  9, 10, 37, 45, 51, 56, 71, 71, 71, 77, 84, 95, 97, 98])

In [5]:
np.sort(a, kind='mergesort')

array([ 3,  9, 10, 37, 45, 51, 56, 71, 71, 71, 77, 84, 95, 97, 98])

In [6]:
# descending order
np.sort(a)[::-1]

array([98, 97, 95, 84, 77, 71, 71, 71, 56, 51, 45, 37, 10,  9,  3])

In [7]:
b

array([[ 2, 61, 37, 74],
       [45,  6,  2, 23],
       [ 6, 71, 77, 38],
       [15, 73, 63, 39],
       [12, 21, 87, 27],
       [25, 95, 28, 63]])

In [8]:
# column wise sorting
np.sort(b, axis=0)

array([[ 2,  6,  2, 23],
       [ 6, 21, 28, 27],
       [12, 61, 37, 38],
       [15, 71, 63, 39],
       [25, 73, 77, 63],
       [45, 95, 87, 74]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [10]:
np.append(a, 150)

array([ 71,  98,  51,  45,  84,  71,  10,  77,   9,  37,  56,  71,  97,
         3,  95, 150])

In [11]:
# 2D array

np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[ 2., 61., 37., 74.,  1.],
       [45.,  6.,  2., 23.,  1.],
       [ 6., 71., 77., 38.,  1.],
       [15., 73., 63., 39.,  1.],
       [12., 21., 87., 27.,  1.],
       [25., 95., 28., 63.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [12]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [16]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [17]:
# benefits:
# -> to create vector column or vector row
# -> mostly ML models accept multiple inputs to generate a result, so to convert single input to multiple inputs

In [18]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [19]:
# code
a.shape

(15,)

In [20]:
np.expand_dims(a, axis=1)

array([[71],
       [98],
       [51],
       [45],
       [84],
       [71],
       [10],
       [77],
       [ 9],
       [37],
       [56],
       [71],
       [97],
       [ 3],
       [95]])

In [21]:
np.expand_dims(a, axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [22]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [23]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  4,  5,  7, 10, 11, 12, 14]),)

In [24]:
# replace all values > 50 with 0
# np.where(condition,true,false)
np.where(a>50,0,a)

array([ 0,  0,  0, 45,  0,  0, 10,  0,  9, 37,  0,  0,  0,  3,  0])

In [25]:
np.where(a%2 == 0,0,a)

array([71,  0, 51, 45,  0, 71,  0, 77,  9, 37,  0, 71, 97,  3, 95])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [26]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [27]:
np.argmax(a)

np.int64(1)

In [28]:
b

array([[ 2, 61, 37, 74],
       [45,  6,  2, 23],
       [ 6, 71, 77, 38],
       [15, 73, 63, 39],
       [12, 21, 87, 27],
       [25, 95, 28, 63]])

In [29]:
np.argmax(b)

np.int64(21)

In [30]:
# row wise
np.argmax(b, axis=1)

array([3, 0, 2, 1, 2, 1])

In [31]:
np.argmax(b, axis=0)

array([1, 5, 4, 0])

In [32]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [33]:
# np.argmin
np.argmin(a)

np.int64(13)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [34]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [35]:
np.cumsum(a)

array([ 71, 169, 220, 265, 349, 420, 430, 507, 516, 553, 609, 680, 777,
       780, 875])

In [36]:
b

array([[ 2, 61, 37, 74],
       [45,  6,  2, 23],
       [ 6, 71, 77, 38],
       [15, 73, 63, 39],
       [12, 21, 87, 27],
       [25, 95, 28, 63]])

In [37]:
np.cumsum(b, axis=0)

array([[  2,  61,  37,  74],
       [ 47,  67,  39,  97],
       [ 53, 138, 116, 135],
       [ 68, 211, 179, 174],
       [ 80, 232, 266, 201],
       [105, 327, 294, 264]])

In [38]:
np.cumsum(b, axis=1)

array([[  2,  63, 100, 174],
       [ 45,  51,  53,  76],
       [  6,  77, 154, 192],
       [ 15,  88, 151, 190],
       [ 12,  33, 120, 147],
       [ 25, 120, 148, 211]])

In [39]:
# np.cumprod
np.cumprod(a)

array([                  71,                 6958,               354858,
                   15968610,           1341363240,          95236790040,
               952367900400,       73332328330800,      659990954977200,
          24419665334156400,  1367501258712758400,  4858869000058088320,
       -8305052910813774976, -6468414658731773312, -5756838147103261312])

In [40]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [41]:
np.percentile(a, 100)

np.float64(98.0)

In [42]:
np.percentile(a, 50)

np.float64(71.0)

In [43]:
np.percentile(a, 0)

np.float64(3.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [44]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [45]:
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 1, 0, 1, 1, 2, 0, 4, 1, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [46]:
np.histogram(a, bins=[0,20,40,60,80,100])

(array([3, 1, 3, 4, 4]), array([  0,  20,  40,  60,  80, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [47]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [48]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [49]:
items = [20,30,40,50,60]
np.isin(a, items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [50]:
a[np.isin(a, items)]

array([], dtype=int64)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [51]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [52]:
np.flip(a)

array([95,  3, 97, 71, 56, 37,  9, 77, 10, 71, 84, 45, 51, 98, 71])

In [53]:
b

array([[ 2, 61, 37, 74],
       [45,  6,  2, 23],
       [ 6, 71, 77, 38],
       [15, 73, 63, 39],
       [12, 21, 87, 27],
       [25, 95, 28, 63]])

In [54]:
np.flip(b, axis=0)

array([[25, 95, 28, 63],
       [12, 21, 87, 27],
       [15, 73, 63, 39],
       [ 6, 71, 77, 38],
       [45,  6,  2, 23],
       [ 2, 61, 37, 74]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [55]:
a

array([71, 98, 51, 45, 84, 71, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [56]:
np.put(a,[2,5],[65,78])

In [57]:
a

array([71, 98, 65, 45, 84, 78, 10, 77,  9, 37, 56, 71, 97,  3, 95])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [58]:
# index
np.delete(a,2)

array([71, 98, 45, 84, 78, 10, 77,  9, 37, 56, 71, 97,  3, 95])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.isin

In [60]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [61]:
np.intersect1d(m,n)

array([3, 4, 5])

In [62]:
np.setdiff1d(m,n)

array([1, 2])

In [63]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [66]:
np.isin(m, 2)

array([False,  True, False, False, False])

In [67]:
m[np.isin(m, 2)]

array([2])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [68]:
a

array([71, 98, 65, 45, 84, 78, 10, 77,  9, 37, 56, 71, 97,  3, 95])

In [69]:
np.clip(a, a_min=15,a_max=75)

array([71, 75, 65, 45, 75, 75, 15, 75, 15, 37, 56, 71, 75, 15, 75])